---
image:
  file: .gitpod.Dockerfile

tasks:
  # Ensure the that Python environment is ready
  - name: Initialize Python, pip and npm
    init: |
      virtualenv .venv
      . .venv/bin/activate
      pip install --upgrade pip setuptools
      pip install -Ur requirements-no-versions.txt
      pip freeze requirements.txt
      npm install control-panel
      gp sync-done python-is-ready # an arbitrary tag.
  # Once the Python environment is set up get the Redis and RabbitMQ servers running.
  - name: Docs Web Server (8000)
    init: gp sync-await python-is-ready
    command: |
      . .venv/bin/activate
      mkdocs serve
    openMode: tab-after
  - name: API Web Server (5000)
    init: gp sync-await python-is-ready
    command: |
      . .venv/bin/activate
      export FLASK_APP=rest_api.flask_app
      export FLASK_ENV=development
      flask run
    openMode: tab-after
  - name: Control panel and Unleash Proxy (3000 and 3001)
    init: gp sync-await python-is-ready
    command: yarn --cwd control-panel start
    openMode: tab-after
  - name: RabbitMQ (5672)
    init: gp sync-await python-is-ready
    command: |
      sudo service rabbitmq-server restart
      sudo rabbitmq-plugins enable rabbitmq_management
      sudo rabbitmqctl add_user the_user the_password
      sudo rabbitmqctl set_user_tags the_user administrator
      sudo rabbitmqctl add_vhost the_vhost
      sudo rabbitmqctl set_permissions -p the_vhost the_user ".*" ".*" ".*"
      gp sync-done rabbitmq # 'rabbitmq' is an arbitrary tag.
  - name: Redis Server
    init: gp sync-await python-is-ready
    command: |
      redis-server --daemonize yes
      gp sync-done redis-is-ready # 'redis-is-ready' is an arbitrary tag.
  # Once Redis is running start the things that rely on it
  - name: Redis Commander (6000)
    init: gp sync-await redis-is-ready
    command: |
      npm install -g redis-commander
      redis-commander --port 6000 --redis-db 1
    openMode: tab-after
  - name: Celery Flower (5555)
    init: gp sync-await redis-is-ready
    command: |
      . .venv/bin/activate
      celery --workdir=celery_app --app=task_broker flower
      gp sync-done celery-monitors-ready # 'celery-monitors-ready' is an arbitrary tag.
    openMode: tab-after
  # Start the Celery Worker once everything else is up and running
  - name: Celery Worker with Watchdog
    init: gp sync-await celery-monitors-ready
    command: >
      . .venv/bin/activate &&
      watchmedo auto-restart --directory=./celery_app/ --pattern=*.py --recursive --
      celery --workdir=celery_app --app=task_broker worker --hostname=worker1@%n --loglevel=INFO --queues=custom_queue

ports:
  - port: 5000
    onOpen: open-preview
    visibility: public
  - port: 5555
    onOpen: open-browser
    visibility: public
  - port: 5672
    onOpen: ignore
    visibility: public
  - port: 6000
    onOpen: open-browser
    visibility: public
  - port: 6379
    onOpen: ignore
    visibility: private
  - port: 8000
    onOpen: open-preview
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public
  - port: 9090
    onOpen: open-preview
    visibility: public
  - port: 15672
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
    - streetsidesoftware.code-spell-checker
...