image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize pip
    init: |
      pip install -r requirements.txt
      gp sync-done pip # 'pip' is an arbitrary tag.
  - name: Docs Web Server (8000)
    init: gp sync-await pip
    command: |
      mkdocs serve
    openMode: tab-after
  - name: API Web Server (5000)
    init: gp sync-await pip
    command: |
      export FLASK_APP=rest_api.flask_app
      export FLASK_ENV=development
      flask run
    openMode: tab-after
  - name: Redis Server
    init: gp sync-await pip
    command: |
      redis-server --daemonize yes
      gp sync-done redis # 'redis' is an arbitrary tag.
  - name: Redis Commander (6000)
    init: gp sync-await redis
    command: |
      npm install -g redis-commander
      redis-commander --port 6000 --redis-db 1
    openMode: tab-after
  - name: Celery Queue
    init: gp sync-await redis
    command: celery --workdir=task_queue --app=celery_app worker --hostname textwork@%n --loglevel=INFO
    openMode: tab-after
  - name: Celery Flower with Watchdog (5555)
    init: gp sync-await redis
    command: watchmedo auto-restart --directory=./task_queue/ --pattern=*.py --recursive -- celery --workdir=task_queue --app=celery_app flower
    openMode: tab-after
  - name: Prometheus (9090)
    init: gp sync-await redis
    command: docker-compose --project-directory ./monitoring up
    openMode: tab-after

ports:
  - port: 5000
    onOpen: open-preview
    visibility: public
  - port: 5555
    onOpen: open-browser
    visibility: public
  - port: 6000
    onOpen: open-browser
    visibility: public
  - port: 6379
    onOpen: ignore
    visibility: private
  - port: 8000
    onOpen: open-preview
    visibility: public
  - port: 9090
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
