image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize pip and npm
    init: |
      pip install -r requirements.txt
      npm install control-panel
      gp sync-done pip-npm # 'pip-npm' is an arbitrary tag.
  - name: Docs Web Server (8000)
    init: gp sync-await pip-npm
    command: |
      mkdocs serve
    openMode: tab-after
  - name: API Web Server (5000)
    init: gp sync-await pip-npm
    command: |
      export FLASK_APP=rest_api.flask_app
      export FLASK_ENV=development
      flask run
    openMode: tab-after
  - name: Redis Server
    init: gp sync-await pip-npm
    command: |
      redis-server --daemonize yes
      gp sync-done redis # 'redis' is an arbitrary tag.
  - name: Redis Commander (6000)
    init: gp sync-await redis
    command: |
      npm install -g redis-commander
      redis-commander --port 6000 --redis-db 1
    openMode: tab-after
  - name: Celery Queue with Watchdog
    init: gp sync-await redis
    command: >
      watchmedo auto-restart --directory=./task_queue/ --pattern=*.py --recursive --
      celery --workdir=task_queue --app=celery_app worker --hostname worker1@%n --loglevel=INFO --queues text_queue,number_queue
    openMode: tab-after
  - name: Celery Flower (5555)
    init: gp sync-await redis
    command: celery --workdir=task_queue --app=celery_app flower
    openMode: tab-after
  - name: Prometheus (9090)
    init: gp sync-await redis
    command: docker-compose --project-directory ./monitoring up
    openMode: tab-after
  - name: Control panel and Unleash Proxy (3000 and 3001)
    init: gp sync-await pip-npm
    command: yarn --cwd control-panel start
    openMode: tab-after

ports:
  - port: 5000
    onOpen: open-preview
    visibility: public
  - port: 5555
    onOpen: open-browser
    visibility: public
  - port: 6000
    onOpen: open-browser
    visibility: public
  - port: 6379
    onOpen: ignore
    visibility: private
  - port: 8000
    onOpen: open-preview
    visibility: public
  - port: 9090
    onOpen: open-preview
    visibility: public

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
    - streetsidesoftware.code-spell-checker
