ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - before: |
      export FLASK_APP=flask_app
      export FLASK_ENV=development
  - name: Initialize Python
    init: >
      pip install -r requirements.txt &&
      gp sync-done pip # 'pip' is an arbitrary tag.
  - name: Webserver
    init: gp sync-await pip
    command: flask run
  - name: Celery Queue
    init: gp sync-await pip
    command: celery --app=celery_app worker --loglevel=INFO
    openMode: tab-after
  - name: Celery Flower
    init: gp sync-await pip
    command: celery --app=celery_app flower
    openMode: tab-after

vscode:
  extensions:
    - ms-python.python
