image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize pip
    init: |
      pip install -r requirements.txt
      gp sync-done pip # 'pip' is an arbitrary tag.
  - name: API Web Server
    init: gp sync-await pip
    command: |
      export FLASK_APP=rest_api.flask_app
      export FLASK_ENV=development
      flask run
  - name: Redis
    init: gp sync-await pip
    command: |
      redis-server --daemonize yes
      gp sync-done redis # 'redis' is an arbitrary tag.
  - name: Redis Commander
    init: gp sync-await redis
    command: |
      npm install -g redis-commander
      redis-commander --port 6000 --redis-db 1
  - name: Celery Queue
    init: gp sync-await redis
    command: celery --workdir=task_queue --app=celery_app worker --loglevel=INFO
    openMode: tab-after
  - name: Celery Flower
    init: gp sync-await redis
    command: celery --workdir=task_queue --app=celery_app flower
    openMode: tab-after
  - name: Docs Web Server
    command: |
      export BUNDLE_GEMFILE=./docs/Gemfile
      bundle install
      bundle exec jekyll serve
    openMode: tab-after

ports:
  - port: 4000
    onOpen: open-preview
    visibility: public
  - port: 5000
    onOpen: open-preview
    visibility: public
  - port: 5555
    onOpen: open-browser
    visibility: public
  - port: 6000
    onOpen: open-browser
    visibility: public
  - port: 6379
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - ms-python.python
