---
image:
  file: .gitpod.Dockerfile

tasks:
  # Ensure the that Python environment is ready
  - name: Initialize Python, pip and npm
    init: |
      virtualenv .venv
      . .venv/bin/activate
      pip install --upgrade pip setuptools
      pip install -Ur requirements.txt
      npm install control-panel
    command: |
      gp sync-done python-is-ready # an arbitrary tag.
  # Once the Python environment is set up get the servers which rely on it.
  - name: Docs Web Server (8000)
    command: |
      gp sync-await python-is-ready
      . .venv/bin/activate
      mkdocs serve
    openMode: tab-after
  - name: API Web Server (5000)
    command: |
      gp sync-await python-is-ready
      . .venv/bin/activate
      export FLASK_APP=rest_api.flask_app
      export FLASK_ENV=development
      flask run
    openMode: tab-after
  - name: Control panel and Unleash Proxy (3000 and 3001)
    command: |
      gp sync-await python-is-ready
      yarn --cwd control-panel start
    openMode: tab-after
  - name: Redis Server
    command: |
      gp sync-await python-is-ready
      redis-server --daemonize yes
      gp sync-done redis-is-ready # 'redis-is-ready' is an arbitrary tag.
  # Once Redis is running start the things that rely on it
  - name: Redis Commander (6000)
    command: |
      gp sync-await redis-is-ready
      npm install -g redis-commander
      redis-commander --port 6000 --redis-db 1
    openMode: tab-after
  # Adjust the Rabbit configuration (has to be done every time because it does not survive a restart).
  - name: RabbitMQ (5672)
    command: |
      gp sync-await redis-is-ready
      sudo service rabbitmq-server restart
      sudo rabbitmq-plugins enable rabbitmq_management
      sudo rabbitmqctl add_user the_user the_password
      sudo rabbitmqctl set_user_tags the_user administrator
      sudo rabbitmqctl add_vhost the_vhost
      sudo rabbitmqctl set_permissions -p the_vhost the_user ".*" ".*" ".*"
      gp sync-done rabbit-is-ready # 'rabbit-is-ready' is an arbitrary tag.
  - name: Celery Flower (5555)
    command: |
      gp sync-await rabbit-is-ready
      . .venv/bin/activate
      celery --workdir=task_queuing --app=celery_app flower
    openMode: tab-after
  - name: Celery Worker with Watchdog
    command: >
      gp sync-await rabbit-is-ready &&
      . .venv/bin/activate &&
      watchmedo auto-restart --directory=./task_queuing/ --pattern=*.py --recursive --
      celery --workdir=task_queuing --app=celery_app worker --hostname=worker1@%n --loglevel=INFO --queues=custom_queue,text_queue,number_queue,ansible_queue

ports:
  - port: 5000
    onOpen: open-preview
    visibility: public
  - port: 5555
    onOpen: open-browser
    visibility: public
  - port: 5672
    onOpen: ignore
    visibility: public
  - port: 6000
    onOpen: open-browser
    visibility: public
  - port: 6379
    onOpen: ignore
    visibility: private
  - port: 8000
    onOpen: open-preview
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public
  - port: 9090
    onOpen: open-preview
    visibility: public
  - port: 15672
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - eamodio.gitlens
    - streetsidesoftware.code-spell-checker
...