ports:
  - port: 5000
    onOpen: open-preview

tasks:
  - before: |
      export FLASK_APP=flask_app
      export FLASK_ENV=development
    init: |
      pip install -r requirements.txt
  - name: Demo API
    command: flask run
    openMode: tab-after
  - name: Celery Queue
    command: celery --app=celery_app worker --loglevel=INFO
    openMode: tab-after
  - name: Celery Flower
    command: celery --app=celery_app flower
    openMode: tab-after

vscode:
  extensions:
    - ms-python.python
