image:
  file: .gitpod.Dockerfile

tasks:
  - name: Initialize Python and Redis
    init: |
      pip install -r requirements.txt
      echo 'eval "$(starship init bash)"' >> $HOME/.bashrc
      source $HOME/.bashrc
      redis-server --daemonize yes
      gp sync-done pip # 'pip' is an arbitrary tag.
  - name: Redis Commander
    init: gp sync-await pip
    command: |
      npm install -g redis-commander
      redis-commander
  - name: Web Server
    init: gp sync-await pip
    command: |
      export FLASK_APP=flask_app
      export FLASK_ENV=development
      flask run
  - name: Celery Queue
    init: gp sync-await pip
    command: celery --app=celery_app worker --loglevel=INFO
    openMode: tab-after
  - name: Celery Flower
    init: gp sync-await pip
    command: celery --app=celery_app flower
    openMode: tab-after

ports:
  - port: 5000
    onOpen: open-preview
  - port: 5555
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
