---
extends: default

ignore: |
  .github/
  .venv/
  .devcontainer/

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length: disable
