---
site_name: Captain Black
repo_url: https://github.com/joejcollins/captain-black
theme:
    name: 'material'
    palette:
        - scheme: default
          primary: indigo
          accent: indigo

plugins:
    - search
    - roamlinks
    - mermaid2

extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    - https://unpkg.com/mermaid/dist/mermaid.min.js
