version: '3'
services:
    prometheus:
        image: prom/prometheus:latest
        container_name: captain-black-prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - '9090:9090'