---
  - hosts: all
    become: yes
    gather_facts: no
    tasks:
  
      - name: Install Apache2 and PHP
        package:
          name:
              - apache2
              - libapache2-mod-php
              - php-intl
              - php-mbstring
              - php-xml
              - php-zip
              - php-xdebug
              - php-curl
              - curl
              - php-gd
              - php-imagick
              - composer
          state: present
