name: Python Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ develop ]


jobs:
  # Check the status of this job before merge.
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # Stop if there are Python syntax errors or undefined names.
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Stop if the linting does not pass.
        flake8 . --count --max-complexity=10 --max-line-length=110 --statistics
    - name: Run celery worker for tests
      run: |
        celery --workdir=task_queue --app=celery_app worker --hostname worker1@%n --loglevel=INFO --queues text_queue,number_queue --detach
    - name: Test with pytest
      run: |
        pytest
