name: Python Tests

on:
  push:
    branches: [ main ]

jobs:
  # Check the status of this job before merge.
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout the captain_black repo.
      uses: actions/checkout@v4
      with:
        clean: true
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
    - name: Install dependencies
      run: |
        make requirements
    - name: Lint with flake8
      run: |
        # Stop if there are Python syntax errors or undefined names.
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Stop if the linting does not pass.
        flake8 . --count --max-complexity=10 --max-line-length=110 --statistics
    - name: Test with pytest
      run: |
        pytest
