---
name: Run the Python Tests

on:
  push:
    branches: [ main ]

jobs:
  run_python_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joejcollins/captain-black-dev:latest
    steps:
      - name: Checkout the repo.
        uses: actions/checkout@v4
        with:
          submodules: false
          clean: true
      - name: Symlink to virtual environment in container image
        run: |
          ln -snf /usr/src/.venv .venv
      - name: Run tests.
        env:
          SOURCERY_TOKEN: ${{ secrets.SOURCERY_TOKEN }}
        run: |
          pwd
          ls -lah
          make report
          make lint
          make test
